export const types = {
  LOGIN_ADMIN_REQUEST: "LOGIN_ADMIN_REQUEST",
  LOGIN_ADMIN_SUCCESS: "LOGIN_ADMIN_SUCCESS",
  LOGIN_ADMIN_FAILURE: "LOGIN_ADMIN_FAILURE",
  //
  GET_ADMIN_REQUEST: "GET_ADMIN_REQUEST",
  GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
  GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE",
  //
  UPDATE_ADMIN_REQUEST: "UPDATE_ADMIN_REQUEST",
  UPDATE_ADMIN_SUCCESS: "UPDATE_ADMIN_SUCCESS",
  UPDATE_ADMIN_FAILURE: "UPDATE_ADMIN_FAILURE",
  //
  UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",
  //
  FETCH_LOGS_REQUEST: "FETCH_LOGS_REQUEST",
  FETCH_LOGS_SUCCESS: "FETCH_LOGS_SUCCESS",
  FETCH_LOGS_FAILURE: "FETCH_LOGS_FAILURE",
  //
  LOGOUT_ADMIN_REQUEST: "LOGOUT_ADMIN_REQUEST"
};
