export const types = {
  FETCH_MODELS_REQUEST: "FETCH_MODELS_REQUEST",
  FETCH_MODELS_SUCCESS: "FETCH_MODELS_SUCCESS",
  FETCH_MODELS_FAILURE: "FETCH_MODELS_FAILURE",
  //
  CREATE_MODEL_REQUEST: "CREATE_MODEL_REQUEST",
  CREATE_MODEL_SUCCESS: "CREATE_MODEL_SUCCESS",
  CREATE_MODEL_FAILURE: "CREATE_MODEL_FAILURE",
  //
  UPDATE_MODEL_REQUEST: "UPDATE_MODEL_REQUEST",
  UPDATE_MODEL_SUCCESS: "UPDATE_MODEL_SUCCESS",
  UPDATE_MODEL_FAILURE: "UPDATE_MODEL_FAILURE",
  //
  DELETE_MODEL_REQUEST: "DELETE_MODEL_REQUEST",
  DELETE_MODEL_SUCCESS: "DELETE_MODEL_SUCCESS",
  DELETE_MODEL_FAILURE: "DELETE_MODEL_FAILURE",
  //
  TRAIN_MODEL_REQUEST: "TRAIN_MODEL_REQUEST",
  TRAIN_MODEL_SUCCESS: "TRAIN_MODEL_SUCCESS",
  TRAIN_MODEL_FAILURE: "TRAIN_MODEL_FAILURE",
  //
  TEST_MODEL_REQUEST: "TEST_MODEL_REQUEST",
  TEST_MODEL_SUCCESS: "TEST_MODEL_SUCCESS",
  TEST_MODEL_FAILURE: "TEST_MODEL_FAILURE"
};
