export const types = {
  FETCH_CONTRIBUTORS_REQUEST: "FETCH_CONTRIBUTORS_REQUEST",
  FETCH_CONTRIBUTORS_SUCCESS: "FETCH_CONTRIBUTORS_SUCCESS",
  FETCH_CONTRIBUTORS_FAILURE: "FETCH_CONTRIBUTORS_FAILURE"
  //
};
