export const types = {
  //
  SHOW_TASK_FORM_REQUEST: "SHOW_TASK_FORM_REQUEST",
  SHOW_TASK_VIEW_REQUEST: "SHOW_TASK_VIEW_REQUEST",
  SHOW_TASK_DISABLE_WARNING_REQUEST: "SHOW_TASK_DISABLE_WARNING_REQUEST",
  SHOW_TASK_DELETE_WARNING_REQUEST: "SHOW_TASK_DELETE_WARNING_REQUEST",
  //
  HIDE_TASK_FORM_REQUEST: "HIDE_TASK_FORM_REQUEST",
  HIDE_TASK_VIEW_REQUEST: "HIDE_TASK_VIEW_REQUEST",
  HIDE_TASK_DISABLE_WARNING_REQUEST: "HIDE_TASK_DISABLE_WARNING_REQUEST",
  HIDE_TASK_DELETE_WARNING_REQUEST: "HIDE_TASK_DELETE_WARNING_REQUEST",
  //
  SHOW_MODEL_FORM_REQUEST: "SHOW_MODEL_FORM_REQUEST",
  SHOW_MODEL_VIEW_REQUEST: "SHOW_MODEL_VIEW_REQUEST",
  SHOW_MODEL_TRAINING_VIEW_REQUEST: "SHOW_MODEL_TRAINING_VIEW_REQUEST",
  SHOW_MODEL_TESTING_VIEW_REQUEST: "SHOW_MODEL_TESTING_VIEW_REQUEST",
  SHOW_MODEL_DELETE_WARNING_REQUEST: "SHOW_MODEL_DELETE_WARNING_REQUEST",
  //
  HIDE_MODEL_FORM_REQUEST: "HIDE_MODEL_FORM_REQUEST",
  HIDE_MODEL_VIEW_REQUEST: "HIDE_MODEL_VIEW_REQUEST",
  HIDE_MODEL_TRAINING_VIEW_REQUEST: "HIDE_MODEL_TRAINING_VIEW_REQUEST",
  HIDE_MODEL_TESTING_VIEW_REQUEST: "HIDE_MODEL_TESTING_VIEW_REQUEST",
  HIDE_MODEL_DELETE_WARNING_REQUEST: "HIDE_MODEL_DELETE_WARNING_REQUEST",
  //
  SHOW_DATASET_VIEW_REQUEST: "SHOW_DATASET_VIEW_REQUEST",
  SHOW_DATASET_DOWNLOAD_REQUEST: "SHOW_DATASET_DOWNLOAD_REQUEST",
  SHOW_DATASET_SPLIT_WARNING_REQUEST: "SHOW_DATASET_SPLIT_WARNING_REQUEST",
  SHOW_DATASET_EMPTY_WARNING_REQUEST: "SHOW_DATASET_EMPTY_WARNING_REQUEST",
  //
  HIDE_DATASET_VIEW_REQUEST: "HIDE_DATASET_VIEW_REQUEST",
  HIDE_DATASET_DOWNLOAD_REQUEST: "HIDE_DATASET_DOWNLOAD_REQUEST",
  HIDE_DATASET_SPLIT_WARNING_REQUEST: "HIDE_DATASET_SPLIT_WARNING_REQUEST",
  HIDE_DATASET_EMPTY_WARNING_REQUEST: "HIDE_DATASET_EMPTY_WARNING_REQUEST",
};
