export const types = {
  FETCH_LINK_DOCUMENTS_REQUEST: "FETCH_LINK_DOCUMENTS_REQUEST",
  FETCH_LINK_DOCUMENTS_SUCCESS: "FETCH_LINK_DOCUMENTS_SUCCESS",
  FETCH_LINK_DOCUMENTS_FAILURE: "FETCH_LINK_DOCUMENTS_FAILURE",
  //
  CREATE_LINK_DOCUMENT_DATA: "CREATE_LINK_DOCUMENT_DATA",
  UPDATE_LINK_DOCUMENT_DATA: "UPDATE_LINK_DOCUMENT_DATA",
  DELETE_LINK_DOCUMENT_DATA: "DELETE_LINK_DOCUMENT_DATA",
};
