export const types = {
  LOGIN_CONTRIBUTOR_REQUEST: "LOGIN_CONTRIBUTOR_REQUEST",
  LOGIN_CONTRIBUTOR_SUCCESS: "LOGIN_CONTRIBUTOR_SUCCESS",
  LOGIN_CONTRIBUTOR_FAILURE: "LOGIN_CONTRIBUTOR_FAILURE",
  //
  GET_CONTRIBUTOR_REQUEST: "GET_CONTRIBUTOR_REQUEST",
  GET_CONTRIBUTOR_SUCCESS: "GET_CONTRIBUTOR_SUCCESS",
  GET_CONTRIBUTOR_FAILURE: "GET_CONTRIBUTOR_FAILURE",
  //
  FETCH_HISTORY_REQUEST: "FETCH_HISTORY_REQUEST",
  FETCH_HISTORY_SUCCESS: "FETCH_HISTORY_SUCCESS",
  FETCH_HISTORY_FAILURE: "FETCH_HISTORY_FAILURE",
  //
  LOGOUT_CONTRIBUTOR_REQUEST: "LOGOUT_CONTRIBUTOR_REQUEST"
};
