export const types = {
  FETCH_FORM_DOCUMENT_REQUEST: "FETCH_FORM_DOCUMENT_REQUEST",
  FETCH_FORM_DOCUMENT_SUCCESS: "FETCH_FORM_DOCUMENT_SUCCESS",
  FETCH_FORM_DOCUMENT_FAILURE: "FETCH_FORM_DOCUMENT_FAILURE",
  //
  CREATE_FORM_DOCUMENT_DATA: "CREATE_FORM_DOCUMENT_DATA",
  UPDATE_FORM_DOCUMENT_DATA: "UPDATE_FORM_DOCUMENT_DATA",
  DELETE_FORM_DOCUMENT_DATA: "DELETE_FORM_DOCUMENT_DATA",
};
