export const types = {
  //
  FETCH_DOCUMENTS_REQUEST: "FETCH_DOCUMENTS_REQUEST",
  FETCH_DOCUMENTS_SUCCESS: "FETCH_DOCUMENTS_SUCCESS",
  FETCH_DOCUMENTS_FAILURE: "FETCH_DOCUMENTS_FAILURE",
  //
  DELETE_DOCUMENTS_REQUEST: "DELETE_DOCUMENTS_REQUEST",
  DELETE_DOCUMENTS_SUCCESS: "DELETE_DOCUMENTS_SUCCESS",
  DELETE_DOCUMENTS_FAILURE: "DELETE_DOCUMENTS_FAILURE",
  //
  CREATE_DOCUMENTS_REQUEST: "CREATE_DOCUMENTS_REQUEST",
  CREATE_DOCUMENTS_SUCCESS: "CREATE_DOCUMENTS_SUCCESS",
  CREATE_DOCUMENTS_FAILURE: "CREATE_DOCUMENTS_FAILURE",
  //
  UPDATE_DOCUMENTS_REQUEST: "UPDATE_DOCUMENTS_REQUEST",
  UPDATE_DOCUMENTS_SUCCESS: "UPDATE_DOCUMENTS_SUCCESS",
  UPDATE_DOCUMENTS_FAILURE: "UPDATE_DOCUMENTS_FAILURE",
  //
  SET_LIST_LIMIT: "SET_LIST_LIMIT",
  SET_LIST_SORT_ORDER: "SET_LIST_SORT_ORDER",
  SET_LIST_SORT_FIELD: "SET_LIST_SORT_FIELD",
  RESET_DOCUMENTS: "RESET_DOCUMENTS",
};
