export const types = {
  FETCH_GLOBAL_STATS_REQUEST: "FETCH_GLOBAL_STATS_REQUEST",
  FETCH_GLOBAL_STATS_SUCCESS: "FETCH_GLOBAL_STATS_SUCCESS",
  FETCH_GLOBAL_STATS_FAILURE: "FETCH_GLOBAL_STATS_FAILURE",
  //
  TOGGLE_SIDEBAR_REQUEST: "TOGGLE_SIDEBAR_REQUEST",
  TOGGLE_SIDEBAR_ITEM_REQUEST: "TOGGLE_SIDEBAR_ITEM_REQUEST",
};
