export const types = {
  FETCH_TABLE_DOCUMENTS_REQUEST: "FETCH_TABLE_DOCUMENTS_REQUEST",
  FETCH_TABLE_DOCUMENTS_SUCCESS: "FETCH_TABLE_DOCUMENTS_SUCCESS",
  FETCH_TABLE_DOCUMENTS_FAILURE: "FETCH_TABLE_DOCUMENTS_FAILURE",
  //
  CREATE_TABLE_DOCUMENT_DATA: "CREATE_TABLE_DOCUMENT_DATA",
  UPDATE_TABLE_DOCUMENT_DATA: "UPDATE_TABLE_DOCUMENT_DATA",
  DELETE_TABLE_DOCUMENT_DATA: "DELETE_TABLE_DOCUMENT_DATA",
};
