export const types = {
  FETCH_TASK_REQUEST: "FETCH_TASK_REQUEST",
  FETCH_TASK_SUCCESS: "FETCH_TASK_SUCCESS",
  FETCH_TASK_FAILURE: "FETCH_TASK_FAILURE",
  //
  RESET_TASK_REQUEST: "RESET_TASK_REQUEST"
};
